version: '3.8'

services:
  bankingapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_FILE=./bank.db
    command: ["./bankingapp", "run"]
